blank_issues_enabled: true
contact_links:
  - name: Ask a question
    about: |
      You've come to seek help or want to discuss something related to stedi.
    url: https://github.com/jopamo/stedi/discussions/new